import Head from "next/head";
import React from "react";
import { ChristmasWrapper } from "./styled";

const ChristmasPage: React.FC = () => {
  return (
    <ChristmasWrapper>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdn.jsdelivr.net/npm/three@0.115.0/build/three.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/three@0.115.0/examples/js/postprocessing/EffectComposer.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/three@0.115.0/examples/js/postprocessing/RenderPass.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/three@0.115.0/examples/js/postprocessing/ShaderPass.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/three@0.115.0/examples/js/shaders/CopyShader.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/three@0.115.0/examples/js/shaders/LuminosityHighPassShader.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/three@0.115.0/examples/js/postprocessing/UnrealBloomPass.js"></script>
      </Head>
      <div id="overlay">
        <ul>
          <li className="title">Bé sẵn sàng chưa</li>
          <li>
            <button className="btn" id="btnA" type="button">
              Bắt đầu thuiii
            </button>
          </li>
        </ul>
      </div>
      <script type="text/javascript" src="/index.js"></script>
    </ChristmasWrapper>
  );
};

export default ChristmasPage;
